### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by DLwbm123** [sahagobinda/GPM#2]
Hi! I have a question about the function get_representation_matrix. Why was the batch_list set to [2 * 12, 100, 100, 125, 125]? And can I set it to another batch_list? Thanks!

**Comment by sahagobinda** [comment]
For CIFAR experiments, the number of samples (n_s) used for representation matrix construction for SVD was chosen to be 125. It is a hyperparameter (please see Table C.7 in the paper). In the earlier layers, to keep the representation matrix size reasonable we used a subset of these 125 samples as reflected in the batch_list. Depending on your problem and experimental setup you can try out different values in the batch_list.
