### ISSUE TITLE
Download wrong fashionMNIST

### ISSUE THREAD

**Issue by sk1123344** [sahagobinda/GPM#4]
HI, thanks for your goord work. I find that the code in `five_datasets.py` downloads the wrong dataset, which is actually downloading MNIST instead of fashionMNIST. And using correct fashionMNIST, the total accuracy of 5 datasets may drop 2-3% according to my experiments. I think maybe you can check your code and figure out this issue.

**Comment by sahagobinda** [comment]
Thanks, will check and update accordingly.
