### ISSUE TITLE
what‘s meaning about 15 in cifar100

### ISSUE THREAD

**Issue by muyuuuu** [sahagobinda/GPM#8]
what's meaning about 15, and why fill zero to parameters' gradient?

https://github.com/sahagobinda/GPM/blob/1a238ec9d2ca30bae8fd1707f161cc6bd093c72a/main_cifar100.py#L150-L157

**Comment by sahagobinda** [comment]
K<15 is used to exclude gradient projections of the final classifier layer. 
fill_(0) is used to stop gradient updates of the batch-norm parameters in the model after task 1.

**Comment by muyuuuu** [comment]
thank you~
